### PR TITLE
Expanding heat map - WIP

### PR DESCRIPTION
**Pull request by magland**
Here's the table-based expanding heat map that groups study sets together. There are at least a couple things that need to be remedied:

1. The heatmap colors need to be computed based on the palette. This would be accomplished in the following two functions in HeatmapViz.js which are presently hard-coded:

```
  compute_bg_color(val) {
    return 'pink';
  }
  compute_fg_color(val) {
    return 'blue';
  }
```

2. Need a prettier expand/collapse icon. Right now I am just using a button with "+" and "-" text.

3. They border styling perhaps could be improved.

Also,  I am finding that it is very natural to want the rows to expand/collapse based on a click of the row. So my feeling is that we should provide both functionalities (as is currently implemented).

image

### CODE REVIEW

**Comment by magland** [comment]
I've updated the PR to have a formula that always puts the "val" for determining color between 0 and 1. Thus when rows are normalized, the count gets divided by the max in the row. I also put a prelim color formula in, but I'd like to change it to the one you were using. See screenshot below.

image

**Comment by elovero** [comment]
TODOs on PR:
1. Resolve the console errors
2. Snake to camel?

**Comment by magland** [comment]
cleaned up code... snake->camel in HeatmapViz.js (but not in ExpandingHeatmapTable.js yet)

Need to change .map() to .forEach where relevant.

**Comment by magland** [comment]
renamed studySortingResults -> groupedUnitResults and map->forEach where appropriate

**Pull request merged**
